config/urls.py
"""
URL configuration for grpahs project.
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('graphs_apps.graphs.urls', namespace='graphs')),
    path("admin/", admin.site.urls),
]

graphs_apps/graphs/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView
from .views import ProjectUpdateView, ProjectCreateView, ProjectDeleteView

app_name = 'graphs'

urlpatterns = [
    path('', ProjectListView.as_view(), name='all'),
    path('projects/<int:pk>/detail',
         ProjectDetailView.as_view(), name='project_detail'),
    path('projects/create/',
         ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/update/',
         ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/',
         ProjectDeleteView.as_view(), name='project_delete'),
]

graphs_apps/account/models.py
from django.contrib.auth import models as auth_models


class User(auth_models.AbstractUser):

    def get_full_name(self):
        return self.first_name + " " + self.last_name

graphs_apps/graphs/models.py
import pandas as pd
from datetime import timedelta, datetime
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _

TOTAL_TIME = 800
NBH_BYDAY_ONPROJECT = 4
NBH_BYDAY = 7


class Project(models.Model):

    subject = models.CharField(max_length=124)
    title = models.CharField(max_length=124)
    description = models.CharField(max_length=512, default="")

    estimate_time = models.DurationField(
        default=timedelta(hours=0)
        )

    nb_days_affected = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(200)]
    )

    estimate_start_date = models.DateField()
    estimate_end_date = models.DateField()
    real_start_date = models.DateField()
    real_end_date = models.DateField()
    real_time = models.DurationField(
        default=timedelta(hours=0)
        )
    real_time_on_project = models.DurationField(
        default=timedelta(hours=0)
        )
    evaluate_date = models.DateField()

    # self.tasks = []
    # self.df = pd.DataFrame([task.__dict__ for task in self.tasks])

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['subject'], name='unique_project')
        ]

    @property
    def pct_total_time(self):
        return self.estimate_time/TOTAL_TIME

    @property
    def nb_hours_on_project(self):
        return self.nb_days_affected*NBH_BYDAY_ONPROJECT

    @property
    def nb_hours_affected(self):
        return self.nb_days_affected*NBH_BYDAY

    @property
    def dataframe(self):
        return pd.DataFrame([task.__dict__ for task in self.project.tasks])

    def __str__(self):
        return self.subject

    def __repr__(self):
        line = self.title + ": " + self.description + "\n"
        line += f"Estimations : {str(self.estimate_time)} soit"
        line += f"{str(self.pct_total_time)}% du total\n"
        line += f"{str(self.nb_days_affected)} jours affectés "
        line += f"soit {str(self.nb_hours_on_project)} heures sur le projet "
        line += f"et {str(self.nb_hours_affected)} heures au total\n"
        line += f"Le projet est prévu de : {self.estimate_start_date} "
        line += f"au {self.estimate_end_date}"
        if self.real_start_date:
            line += f"Il s'est effectivement déroulé du {self.real_start_date}"
            line += f" au {self.real_end_date}\n"
            line += f"pour une durée de {self.real_time} "
            +"heure soit {self.real_time_on_project} "
            line += f"{self.real_time_on_project} sur le projet"
        now = datetime.date
        print(self.evaluate_date)
        print(type(self.evaluate_date))
        if len(self.evaluate_date) > 0:
            a_date = datetime.datetime.strptime(self.evaluate_date, "%d/%m/%Y")
            if now < a_date:
                line += f"La soutenance aura lieu le {self.evaluate_date}"
            else:
                line += f"La soutenance a eu lieu le {self.evaluate_date}"
        return line


class Task(models.Model):

    class Category(models.TextChoices):
        ORGANIZATION = "1ORG", _('Organisation')
        FORUM = "2FRM", _('Forum')
        MENTORAT = "3MEN", _('Mentorat')
        DEVELOPMENT = "6DEV", _('Developpement')
        ANALYSE = "5ANA", _('Analyse')
        FORMATION = "4FOR", _('Formation')
        EVALUATION = "7EVL", _('Evaluation')

    date_task = models.DateField()
    subject = models.ForeignKey(
        to=Project, related_name="project_task",
        on_delete=models.CASCADE,
        blank=True, null=True
        )
    category = models.CharField(
        max_length=4, choices=Category.choices, default=""
        )
    description = models.CharField(max_length=512, default="", blank=True)
    estimate_time = models.DurationField(
        default=timedelta(hours=0)
        )
    real_time = models.DurationField(
        default=timedelta(hours=0)
        )

    def __str__(self):
        ch = str(self.date_task) + "- (" + self.subject.title + ")"
        ch += self.category + "\n"
        ch += self.description + "\n"
        ch += "Estimé : " + str(self.estimate_time)
        ch += " --- Réalisé : " + str(self.real_time)
        return ch

graphs_apps/account/views.py
from django.shortcuts import render

# Create your views here.

graphs_apps/graphs/views.py
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models_project import Project
# from .models_task import Task


class ProjectBaseView(View):
    model = Project
    fields = '__all__'
    sucess_url = reverse_lazy('graphs:all')


class ProjectListView(ProjectBaseView, ListView):
    ...


class ProjectDetailView(ProjectBaseView, DetailView):
    # records = Task.objects.filter(subject=).values_list(*fields)
    ...


class ProjectCreateView(ProjectBaseView, CreateView):
    ...


class ProjectUpdateView(ProjectBaseView, UpdateView):
    ...


class ProjectDeleteView(ProjectBaseView, DeleteView):
    ...

graphs_apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

    {% include "base/head.html"%}
    <body id="page-top">    
        
        {% include "base/header.html"%}

        <main>
            <div id="content">
            {% block content %}
            {% endblock content %}
            </div>
        </main>
    
        {% include "base/footer.html"%}
    </body>

</html>

graphs_apps/templates/base/footer.html
{% load static %}
<footer id="footer" class="footer">
    <img class="footer__logo" src="{% static "assets/logo.png" %}" alt="logo graphs">
    <!-- &copy; 2023 Sylvie Bricout -->
    <!-- <nav class="footer__menu">
        {% include 'navbar/footer_navbar.html' %}                
    </nav> -->
</footer>

graphs_apps/templates/base/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}" />
    
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />

    <link href="{% static "css/graphs.css" %}" rel="stylesheet">
    <!-- <link href="{% static "css/styles.css" %}" rel="stylesheet"> -->
    <!-- <link href="../static/css/review.css" rel="stylesheet"> -->
</head>

graphs_apps/templates/base/header.html
<header id="header">
    <a href="{% url 'graphs:all' %}"><h1>GRAPHS</h1></a>
    
    {% if user.is_authenticated %}
        <div class="user_connected">
        <p>Vous êtes connecté en tant que {{request.user}}</p>
        </div>

        <!-- Navigation-->
        {% include 'navbar/navbar.html' %}                

    {% endif %}
</header>

graphs_apps/templates/base/message.html
<div>
    {% for message in messages%}
        <p id="messages">{{message}}</p>
    {% endfor %}
</div>

graphs_apps/templates/graphs/project_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Description du projet</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for label, value in project.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>


           {{project.dataframe}}
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'graphs:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

graphs_apps/templates/graphs/project_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <!-- <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'graphs:all' %}'; return false;" value="Cancel"> -->
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

graphs_apps/templates/graphs/project_list.html
{% extends 'base.html' %}

{% block content %}
{% for project in project_list %}
    {% for colname in project.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">My Films</h1>
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Subject</th>
                    <th class="text-center" scope="col">Title</th>
                    <th class="text-center" scope="col">Description</th>
                    <th class="text-center" scope="col">estimate_time</th>
                    <th class="text-center" scope="col">nb_days_affected</th>
                    <th class="text-center" scope="col">estimate_start_date</th>
                    <th class="text-center" scope="col">estimate_end_date</th>
                    <th class="text-center" scope="col">real_start_date</th>
                    <th class="text-center" scope="col">real_end_date</th>
                    <th class="text-center" scope="col">real_time</th>
                    <th class="text-center" scope="col">real_time_on_project</th>
                    <th class="text-center" scope="col">evaluate_date</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for project in project_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{% url 'graphs:project_detail' project.id %}">{{project.subject}}</a></td>
                    <td class="text-center">{{project.title}}</td>
                    <td class="text-center">{{project.description}}</td>
                    <td class="text-center">{{project.estimate_time}}</td>
                    <td class="text-center">{{project.nb_days_affected}}</td>
                    <td class="text-center">{{project.estimate_start_date}}</td>
                    <td class="text-center">{{project.estimate_end_date}}</td>
                    <td class="text-center">{{project.real_start_date}}</td>
                    <td class="text-center">{{project.real_end_date}}</td>
                    <td class="text-center">{{project.real_time}}</td>
                    <td class="text-center">{{project.real_time_on_project}}</td>
                    <td class="text-center">{{project.evaluate_date}}</td>
                    <!-- <td><a href="{% url 'graphs:project_update' project.id %} ">Update</a></td>
                    <td><a href="{% url 'graphs:project_delete' project.id %}">Delete</a></td> -->
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <!-- <div class="d-flex justify-content-center">
            <a href="{% url 'graphs:project_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div> -->
    </div>
        
</div>

{% endblock content %}

graphs_apps/templates/navbar/footer_navbar.html
{% load static %}
<ul>
    <li><a class="footer__link" href="">a propos</a></li>
    <li><a class="footer__link" href="">nous contacter</a></li>

</ul>

graphs_apps/templates/navbar/navbar.html
{% load static %}
<nav class="header__menu">
<ul>
    <li>
        <a class="btn" href="{% url 'graphs:all' %}">flux</a>
    </li>

</ul>
</nav>